### ISSUE TITLE
undefined method `decode' for URI:Module with Ruby 3.0.0

### ISSUE THREAD

**Issue by andrewkendall** [pdfkit/pdfkit#485]
Using Ruby 3.0.0 I'm seeing the error:

**undefined method `decode' for URI:Module**

I believe it's because decode has been deprecated and is now removed: https://github.com/ruby/uri/commit/61c6a47ebf

Source of the issue for me is: `url_needs_escaping?` in https://github.com/pdfkit/pdfkit/blob/master/lib/pdfkit/source.rb

**Comment by mtasaka** [comment]
This issue now affects Fedora 34 (rawhide), Fedora 34 uses ruby 3.0: https://koji.fedoraproject.org/koji/taskinfo?taskID=60739087 . Especially, testsuite does pass with ruby 3.0

```
+ xvfb-run -n 98 rspec spec/
Failures:
  1) PDFKit#command does not shell escape source URLs
     Failure/Error: URI::decode(@source) == @source
     NoMethodError:
       undefined method `decode' for URI:Module
     # ./lib/pdfkit/source.rb:45:in `url_needs_escaping?'
     # ./lib/pdfkit/source.rb:41:in `shell_safe_url'
     # ./lib/pdfkit/source.rb:28:in `to_input_for_command'
     # ./lib/pdfkit/pdfkit.rb:53:in `command'
     # ./spec/pdfkit_spec.rb:196:in `block (3 levels) in <top (required)>'
  2) PDFKit#command specifies the URL to the source if it is a url
     Failure/Error: URI::decode(@source) == @source
     NoMethodError:
       undefined method `decode' for URI:Module
     # ./lib/pdfkit/source.rb:45:in `url_needs_escaping?'
     # ./lib/pdfkit/source.rb:41:in `shell_safe_url'
     # ./lib/pdfkit/source.rb:28:in `to_input_for_command'
     # ./lib/pdfkit/pdfkit.rb:53:in `command'
     # ./spec/pdfkit_spec.rb:247:in `block (3 levels) in <top (required)>'
  3) PDFKit#to_pdf throws an error if it is unable to connect
     Failure/Error: expect { pdfkit.to_pdf }.to raise_error PDFKit::ImproperWkhtmltopdfExitStatus, /exitstatus=1/
       expected PDFKit::ImproperWkhtmltopdfExitStatus with message matching /exitstatus=1/, got #<NoMethodError: undefined method `decode' for URI:Module> with backtrace:
         # ./lib/pdfkit/source.rb:45:in `url_needs_escaping?'
         # ./lib/pdfkit/source.rb:41:in `shell_safe_url'
         # ./lib/pdfkit/source.rb:28:in `to_input_for_command'
         # ./lib/pdfkit/pdfkit.rb:53:in `command'
         # ./lib/pdfkit/pdfkit.rb:72:in `to_pdf'
         # ./spec/pdfkit_spec.rb:515:in `block (4 levels) in <top (required)>'
         # ./spec/pdfkit_spec.rb:515:in `block (3 levels) in <top (required)>'
     # ./spec/pdfkit_spec.rb:515:in `block (3 levels) in <top (required)>'
  4) PDFKit::Source#to_input_for_command URI escapes source URLs and encloses them in quotes to accomodate ampersands
     Failure/Error: URI::decode(@source) == @source
     NoMethodError:
       undefined method `decode' for URI:Module
     # ./lib/pdfkit/source.rb:45:in `url_needs_escaping?'
     # ./lib/pdfkit/source.rb:41:in `shell_safe_url'
     # ./lib/pdfkit/source.rb:28:in `to_input_for_command'
     # ./spec/source_spec.rb:78:in `block (3 levels) in <top (required)>'
  5) PDFKit::Source#to_input_for_command does not URI escape previously escaped source URLs
     Failure/Error: URI::decode(@source) == @source
     NoMethodError:
       undefined method `decode' for URI:Module
     # ./lib/pdfkit/source.rb:45:in `url_needs_escaping?'
     # ./lib/pdfkit/source.rb:41:in `shell_safe_url'
     # ./lib/pdfkit/source.rb:28:in `to_input_for_command'
     # ./spec/source_spec.rb:83:in `block (3 levels) in <top (required)>'
```
